# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClipMergeExport
                                 A QGIS plugin
 Clips layers to a 500m grid, merges geometry, and exports as GeoJSON and PNG.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-21
        copyright            : (C) 2024 by Shubhangam
        email                : shubhangam_g@iirs.gov.in
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ClipMergeExport class from file ClipMergeExport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .export import ClipMergeExport
    return ClipMergeExport(iface)
